
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using Microsoft.Win32;

public sealed partial class MainForm : Form
{
    void RestoreTextFieldFromCommitted(string key,int idx){if(committedPlain==null)return;int o=CharacterOffset(idx);if(key=="Level")session.Plain[o+0x01]=committedPlain[o+0x01];else if(key=="Gold")CCSaveCrypto.WriteI32BE(session.Plain,o+0x13,CCSaveCrypto.ReadI32BE(committedPlain,o+0x13));else if(key=="XP")CCSaveCrypto.WriteI32BE(session.Plain,o+0x02,CCSaveCrypto.ReadI32BE(committedPlain,o+0x02));else if(key=="Potions")session.Plain[o+0x0F]=committedPlain[o+0x0F];else if(key=="Bombs")session.Plain[o+0x10]=committedPlain[o+0x10];else if(key=="Sandwiches")session.Plain[o+0x11]=committedPlain[o+0x11];else if(key=="Strength")session.Plain[o+0x08]=committedPlain[o+0x08];else if(key=="Defense")session.Plain[o+0x09]=committedPlain[o+0x09];else if(key=="Magic")session.Plain[o+0x0A]=committedPlain[o+0x0A];else if(key=="Agility")session.Plain[o+0x0B]=committedPlain[o+0x0B];}
    const int MaxNaturalXp=113680;
    static int MinXpForLevel(int level){if(level<=1)return 0;if(level>99)level=99;return 10*(level-1)*(level+17);} static int MaxXpForLevel(int level){if(level>=99)return MaxNaturalXp;if(level<1)level=1;return MinXpForLevel(level+1)-1;} static int NaturalLevelFromXp(int xp){if(xp<=0)return 1;if(xp>=MaxNaturalXp)return 99;for(int level=2;level<=99;level++)if(xp<MinXpForLevel(level))return level-1;return 99;} static int ClampXpToLevelBand(int xp,int level){int min=MinXpForLevel(level),max=MaxXpForLevel(level);if(xp<min)return min;if(xp>max)return max;return xp;} static bool IsXpCompatibleWithLevel(int xp,int level){if(level<1||level>99)return false;return xp>=MinXpForLevel(level)&&xp<=MaxXpForLevel(level);} static int NaturalStatBudgetForLevel(int level){if(level<=1)return 0;if(level<=20)return 2*(level-1);if(level>=78)return 96;return 38+(level-20);} static int NaturalStatPointsUsed(byte[] plain,int o){int used=0;for(int k=0x08;k<=0x0B;k++){int stat=plain[o+k];if(stat>1)used+=stat-1;}return used;} static bool StatsFitNaturalBudget(byte[] plain,int o,int level){for(int k=0x08;k<=0x0B;k++){int stat=plain[o+k];if(stat<1||stat>25)return false;}return NaturalStatPointsUsed(plain,o)<=NaturalStatBudgetForLevel(level);}
    void UpdateCharacterBalanceUi(){if(session==null){balanceStateLabel.Text="Current: —";balanceStateLabel.ForeColor=Muted;balancePointsLabel.Text="Load a save first";balanceCharacterButton.Enabled=false;return;}int idx=SelectedIndex,o=CharacterOffset(idx);int level=Math.Min(99,session.Plain[o+0x01]+1);int xp=CCSaveCrypto.ReadI32BE(session.Plain,o+0x02);int budget=NaturalStatBudgetForLevel(level),used=NaturalStatPointsUsed(session.Plain,o);bool balanced=IsXpCompatibleWithLevel(xp,level)&&StatsFitNaturalBudget(session.Plain,o,level);balanceStateLabel.Text=balanced?"Current: Balanced for Level "+level.ToString(CultureInfo.InvariantCulture):"Current: Custom / Unbalanced";balanceStateLabel.ForeColor=balanced?GoodTextColor:WarnTextColor;balancePointsLabel.Text=budget.ToString(CultureInfo.InvariantCulture)+" points available  •  "+used.ToString(CultureInfo.InvariantCulture)+" used";balanceCharacterButton.Enabled=true;}
    bool CharacterFieldChangedFromCommitted(int idx,int relativeOffset){if(session==null||committedPlain==null)return false;int o=CharacterOffset(idx)+relativeOffset;return session.Plain[o]!=committedPlain[o];} bool CharacterXpChangedFromCommitted(int idx){if(session==null||committedPlain==null)return false;int o=CharacterOffset(idx)+0x02;return CCSaveCrypto.ReadI32BE(session.Plain,o)!=CCSaveCrypto.ReadI32BE(committedPlain,o);} bool AnyCharacterStatChangedFromCommitted(int idx){for(int k=0x08;k<=0x0B;k++)if(CharacterFieldChangedFromCommitted(idx,k))return true;return false;}
    void BalanceStatsToLevelBudget(int idx,int level){int o=CharacterOffset(idx);int[] offsets=new int[]{0x08,0x09,0x0A,0x0B};int[] values=new int[4];bool[] changed=new bool[4];for(int i=0;i<4;i++){values[i]=session.Plain[o+offsets[i]];changed[i]=committedPlain!=null&&session.Plain[o+offsets[i]]!=committedPlain[o+offsets[i]];if(values[i]<1)values[i]=1;if(values[i]>25)values[i]=25;}int budget=NaturalStatBudgetForLevel(level),used=0;for(int i=0;i<4;i++)used+=values[i]-1;while(used>budget){int best=-1;for(int i=0;i<4;i++){if(values[i]<=1)continue;if(best<0||(changed[i]&&!changed[best])||(changed[i]==changed[best]&&values[i]>values[best]))best=i;}if(best<0)break;values[best]--;used--;}for(int i=0;i<4;i++)session.Plain[o+offsets[i]]=(byte)values[i];}
    void BalanceCharacter(){EnsureLoaded();int idx=SelectedIndex,o=CharacterOffset(idx);byte beforeLevel=session.Plain[o+0x01];int beforeXp=CCSaveCrypto.ReadI32BE(session.Plain,o+0x02);byte[] beforeStats=new byte[]{session.Plain[o+0x08],session.Plain[o+0x09],session.Plain[o+0x0A],session.Plain[o+0x0B]};bool levelChanged=CharacterFieldChangedFromCommitted(idx,0x01),xpChanged=CharacterXpChangedFromCommitted(idx),statsChanged=AnyCharacterStatChangedFromCommitted(idx);int level=session.Plain[o+0x01]+1;if(level<1)level=1;if(level>99)level=99;int xp=CCSaveCrypto.ReadI32BE(session.Plain,o+0x02);string reference;if(xpChanged&&!levelChanged){if(xp<0)xp=0;if(xp>MaxNaturalXp)xp=MaxNaturalXp;level=NaturalLevelFromXp(xp);session.Plain[o+0x01]=(byte)(level-1);CCSaveCrypto.WriteI32BE(session.Plain,o+0x02,xp);reference="XP";}else if(levelChanged){xp=ClampXpToLevelBand(xp,level);CCSaveCrypto.WriteI32BE(session.Plain,o+0x02,xp);reference="Level";}else if(statsChanged){reference="current Level/XP";}else{if(xp<0)xp=0;if(xp>MaxNaturalXp)xp=MaxNaturalXp;level=NaturalLevelFromXp(xp);session.Plain[o+0x01]=(byte)(level-1);CCSaveCrypto.WriteI32BE(session.Plain,o+0x02,xp);reference="current XP";}BalanceStatsToLevelBudget(idx,level);bool changedBalance=beforeLevel!=session.Plain[o+0x01]||beforeXp!=CCSaveCrypto.ReadI32BE(session.Plain,o+0x02)||beforeStats[0]!=session.Plain[o+0x08]||beforeStats[1]!=session.Plain[o+0x09]||beforeStats[2]!=session.Plain[o+0x0A]||beforeStats[3]!=session.Plain[o+0x0B];PopulateList();SelectCharacter(idx);UpdateDetails();if(changedBalance)MarkPending("Character balanced using "+reference+" for "+CharacterNames[idx],false);else{UpdatePendingUi();UpdateCharacterBalanceUi();SetStatus(HasPendingChanges()?CharacterNames[idx]+" already fits the natural balance rules. Other staged changes remain.":CharacterNames[idx]+" already fits the natural balance rules.");}}
    void StageEquipmentSelection(){if(suppressControlEvents||session==null||weaponCombo.SelectedItem==null||petCombo.SelectedItem==null)return;int idx=SelectedIndex,o=CharacterOffset(idx),weapon=SelectedComboValue(weaponCombo),pet=SelectedComboValue(petCombo);if(weapon<0||weapon>255||pet<0||pet>255)return;session.Plain[o+0x06]=(byte)weapon;session.Plain[o+0x07]=(byte)pet;MarkPending("Equipment staged for "+CharacterNames[idx],false);selectedWeapon.Text=WeaponDisplayName(weapon);selectedPet.Text=PetDisplayName(pet);}
    void ClearDraftInputsSilent(){suppressControlEvents=true;try{foreach(TextBox tb in edits.Values){tb.Text="";tb.BackColor=InputSurface;}}finally{suppressControlEvents=false;}}
    bool HasInvalidVisibleInputs(){foreach(KeyValuePair<string,TextBox> kv in edits)if(!IsDraftFieldValid(kv.Key,kv.Value.Text))return true;return false;}
}
