
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using Microsoft.Win32;

public sealed partial class MainForm : Form
{
    void PopulateProgressControls(int normalCount,bool insaneUnlocked,int insaneCount,int skull,byte collects){PopulateProgressCombo(normalProgressCombo,normalCount);PopulateProgressCombo(insaneProgressCombo,insaneCount);progressApplyButton.Enabled=session!=null;insaneProgressApplyButton.Enabled=session!=null;string normalRelics=RelicSummary((byte)(collects&0x0F));string insaneRelics=RelicSummary((byte)((collects>>4)&0x0F));progressPrereqSummary.Text="Normal relics: "+normalRelics+"     |     Insane relics: "+insaneRelics+"     |     Insane unlocked: "+(insaneUnlocked?"Yes":"No")+"     |     Skull: "+SkullDisplayName(skull);UpdateProgressPreview();}
    void PopulateProgressCombo(ComboBox combo,int current){combo.BeginUpdate();combo.Items.Clear();for(int i=0;i<ProgressNames.Length;i++)combo.Items.Add(new ComboItem(ProgressNames[i],i));if(current>=ProgressNames.Length)combo.Items.Add(new ComboItem("Keep current: "+current.ToString(CultureInfo.InvariantCulture)+" checkpoints",current));SelectComboValue(combo,current);combo.EndUpdate();}
    static void SelectComboValue(ComboBox combo,int value){combo.SelectedIndex=-1;for(int i=0;i<combo.Items.Count;i++){ComboItem ci=combo.Items[i] as ComboItem;if(ci!=null&&ci.Value==value){combo.SelectedIndex=i;return;}}}
    static int SelectedComboValue(ComboBox combo){ComboItem ci=combo.SelectedItem as ComboItem;if(ci==null)throw new InvalidOperationException("Choose a value first.");return ci.Value;}
    static string RelicSummary(byte nibble){if((nibble&0x0F)==0)return"None";List<string> parts=new List<string>();if((nibble&0x01)!=0)parts.Add("Compass");if((nibble&0x02)!=0)parts.Add("Wheel");if((nibble&0x04)!=0)parts.Add("Telescope");if((nibble&0x08)!=0)parts.Add("Horn");return String.Join(", ",parts.ToArray());}
    void UpdateProgressPreview(){if(session==null){normalProgressPreview.Text="Load a save first.";insaneProgressPreview.Text="Load a save first.";return;}int idx=SelectedIndex,o=CharacterOffset(idx);int currentNormal=CountProgressBits(session.Plain,o+0x0C),currentInsane=CountProgressBits(session.Plain,o+0x18);int targetNormal=normalProgressCombo.SelectedItem==null?currentNormal:SelectedComboValue(normalProgressCombo);int targetInsane=insaneProgressCombo.SelectedItem==null?currentInsane:SelectedComboValue(insaneProgressCombo);normalProgressPreview.Text=BuildProgressPreview(false,currentNormal,targetNormal);insaneProgressPreview.Text=BuildProgressPreview(true,currentInsane,targetInsane);}
    string BuildProgressPreview(bool insane,int current,int target){if(target<current)return"Blocked: this would move progress backward.\r\nUse Restore Latest / Backups instead.";List<string> lines=new List<string>();if(target==current)lines.Add("Checkpoint: no change");else lines.Add("Checkpoints: "+current.ToString(CultureInfo.InvariantCulture)+" → "+target.ToString(CultureInfo.InvariantCulture)+" (earlier included)");List<string> relics=new List<string>();if(target>=10)relics.Add("Compass");if(target>=8)relics.Add("Wheel");if(target>=9)relics.Add("Telescope");if(target>=13)relics.Add("Horn");if(relics.Count>0)lines.Add("Relics ensured: "+String.Join(", ",relics.ToArray()));if(insane&&target>0)lines.Add("Also: complete Normal + enable Insane");return String.Join("\r\n",lines.ToArray());}
    static void ApplyNormalPrerequisites(byte[] data,int o,int target){byte flags=data[o+0x12];if(target>=8)flags|=0x02;if(target>=9)flags|=0x04;if(target>=10)flags|=0x07;if(target>=13)flags|=0x08;data[o+0x12]=flags;}
    static void ApplyInsanePrerequisites(byte[] data,int o,int target){byte flags=data[o+0x12];flags|=0x0F;if(target>=8)flags|=0x20;if(target>=9)flags|=0x40;if(target>=10)flags|=0x70;if(target>=13)flags|=0x80;data[o+0x12]=flags;}
    static bool BytesEqual(byte[] a,byte[] b){if(Object.ReferenceEquals(a,b))return true;if(a==null||b==null||a.Length!=b.Length)return false;for(int i=0;i<a.Length;i++)if(a[i]!=b[i])return false;return true;}
    bool HasPendingChanges(){return session!=null&&committedPlain!=null&&!BytesEqual(session.Plain,committedPlain);}
    void UpdatePendingUi(){bool dirty=HasPendingChanges();if(!dirty)pendingDangerous=false;applyPendingButton.Enabled=dirty;discardPendingButton.Enabled=dirty;overviewApplyButton.Enabled=dirty;statsApplyButton.Enabled=dirty;equipmentApplyButton.Enabled=dirty;if(session==null){pendingLabel.Text="Load a save first";pendingLabel.ForeColor=Muted;saveStateLabel.Text="Not loaded";saveStateLabel.ForeColor=HeaderWarn;UpdateLoadAvailabilityUi();return;}if(dirty){pendingLabel.Text="Staged changes ready";pendingLabel.ForeColor=WarnTextColor;saveStateLabel.Text="Unsaved";saveStateLabel.ForeColor=HeaderWarn;}else{pendingLabel.Text="No staged changes";pendingLabel.ForeColor=Muted;saveStateLabel.Text="Loaded";saveStateLabel.ForeColor=HeaderGood;}UpdateLoadAvailabilityUi();}
    void MarkPending(string message,bool dangerous){if(dangerous)pendingDangerous=true;UpdatePendingUi();UpdateCharacterBalanceUi();if(!String.IsNullOrEmpty(message))SetStatus(message+" — not saved yet.");}
    void StageTextField(string key,TextBox tb){if(suppressControlEvents||session==null||committedPlain==null)return;int idx=SelectedIndex,o=CharacterOffset(idx);string raw=tb.Text.Trim();int min,max;if(!TryGetFieldRange(key,out min,out max))return;if(raw.Length==0){RestoreTextFieldFromCommitted(key,idx);tb.BackColor=InputSurface;UpdateStagedCharacterValueDisplays(idx);UpdatePendingUi();UpdateCharacterBalanceUi();return;}int value;if(!Int32.TryParse(raw,NumberStyles.Integer,CultureInfo.InvariantCulture,out value)||value<min||value>max){tb.BackColor=InvalidInput;SetStatus(key+" is outside the allowed range "+min+"–"+max+".");return;}tb.BackColor=InputSurface;if(key=="Level")session.Plain[o+0x01]=(byte)(value-1);else if(key=="Gold")CCSaveCrypto.WriteI32BE(session.Plain,o+0x13,value);else if(key=="XP")CCSaveCrypto.WriteI32BE(session.Plain,o+0x02,value);else if(key=="Potions")session.Plain[o+0x0F]=(byte)value;else if(key=="Bombs")session.Plain[o+0x10]=(byte)value;else if(key=="Sandwiches")session.Plain[o+0x11]=(byte)value;else if(key=="Strength")session.Plain[o+0x08]=(byte)value;else if(key=="Defense")session.Plain[o+0x09]=(byte)value;else if(key=="Magic")session.Plain[o+0x0A]=(byte)value;else if(key=="Agility")session.Plain[o+0x0B]=(byte)value;bool dangerous=(key=="Level"&&value>99)||((key=="Strength"||key=="Defense"||key=="Magic"||key=="Agility")&&value>25);UpdateStagedCharacterValueDisplays(idx);MarkPending(key+" staged for "+CharacterNames[idx],dangerous);}
    void UpdateStagedCharacterValueDisplays(int idx){if(session==null)return;CharacterData c=ReadCharacter(session.Plain,idx);if(summary.ContainsKey("Level"))summary["Level"].Text=c.Level.ToString(CultureInfo.InvariantCulture);if(summary.ContainsKey("XP"))summary["XP"].Text=c.XP.ToString("N0",CultureInfo.InvariantCulture);if(summary.ContainsKey("Gold"))summary["Gold"].Text=c.Gold.ToString("N0",CultureInfo.InvariantCulture);if(summary.ContainsKey("Strength"))summary["Strength"].Text=c.Strength.ToString(CultureInfo.InvariantCulture);if(summary.ContainsKey("Defense"))summary["Defense"].Text=c.Defense.ToString(CultureInfo.InvariantCulture);if(summary.ContainsKey("Magic"))summary["Magic"].Text=c.Magic.ToString(CultureInfo.InvariantCulture);if(summary.ContainsKey("Agility"))summary["Agility"].Text=c.Agility.ToString(CultureInfo.InvariantCulture);if(summary.ContainsKey("Potions"))summary["Potions"].Text=c.Potions.ToString(CultureInfo.InvariantCulture);if(summary.ContainsKey("Bombs"))summary["Bombs"].Text=c.Bombs.ToString(CultureInfo.InvariantCulture);if(summary.ContainsKey("Sandwiches"))summary["Sandwiches"].Text=c.Sandwiches.ToString(CultureInfo.InvariantCulture);currentLevelOverrideLabel.Text="Current • Lv "+c.Level.ToString(CultureInfo.InvariantCulture)+" • STR "+c.Strength.ToString(CultureInfo.InvariantCulture)+" • DEF "+c.Defense.ToString(CultureInfo.InvariantCulture)+" • MAG "+c.Magic.ToString(CultureInfo.InvariantCulture)+" • AGI "+c.Agility.ToString(CultureInfo.InvariantCulture);}
}
