
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using Microsoft.Win32;

public sealed partial class MainForm : Form
{
    void BuildProgressTab()
    {
        TabPage page=CreateTab("Progress"); TableLayoutPanel layout=CreatePageLayout(page); Panel safe=NewCallout(0,0,820,72,"SAFE PROGRESSION","Forward-only staging. Earlier checkpoints and required relics are added automatically to avoid broken progression.",Good,Color.FromArgb(239,249,241)); AddFullRow(layout,safe,72); Panel normalCard=BuildProgressModeCard(false); Panel insaneCard=BuildProgressModeCard(true); AddFullRow(layout,NewTwoColumnRow(normalCard,insaneCard),254);
        Panel prereq=NewCard(0,0,820,86); prereq.Controls.Add(NewSectionTitle("Current Prerequisites",16,12)); progressPrereqSummary.ForeColor=Muted; progressPrereqSummary.Tag="MutedText"; progressPrereqSummary.AutoSize=false; progressPrereqSummary.AutoEllipsis=true; progressPrereqSummary.Size=new Size(786,38); progressPrereqSummary.Location=new Point(18,42); progressPrereqSummary.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right; prereq.Controls.Add(progressPrereqSummary); AddFullRow(layout,prereq,86);
        Panel presets=NewCard(0,0,820,132); presets.Controls.Add(NewSectionTitle("Completion Presets",16,12)); Label presetDesc=NewMutedLabel("Insane completion also completes Normal. Some map changes appear after the game reloads.",16,40); presets.Controls.Add(presetDesc); Button normalBtn=NewActionButton(presets,"Complete Normal",Accent,delegate{TryUiAction(CompleteNormal);}); ConfigureButton(normalBtn,"Complete Normal",18,76,150,38); Button insaneBtn=NewActionButton(presets,"Complete Insane",Warn,delegate{TryUiAction(CompleteInsane);}); ConfigureButton(insaneBtn,"Complete Insane",182,76,150,38); Button restoreBtn=NewActionButton(presets,"Restore Latest",Good,delegate{TryUiAction(RestoreLatestBackup);}); ConfigureButton(restoreBtn,"Restore Latest",346,76,144,38); AddFullRow(layout,presets,132);
    }
    Panel BuildProgressModeCard(bool insane){Panel card=NewCard(0,0,400,254);card.Controls.Add(NewSectionTitle(insane?"Insane Mode":"Normal Mode",16,12));card.Controls.Add(NewMutedLabel("Advance to",18,52));ComboBox combo=insane?insaneProgressCombo:normalProgressCombo;combo.DropDownStyle=ComboBoxStyle.DropDownList;combo.Location=new Point(108,48);combo.Size=new Size(274,28);combo.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;combo.SelectedIndexChanged+=delegate{UpdateProgressPreview();};card.Controls.Add(combo);Label preview=insane?insaneProgressPreview:normalProgressPreview;preview.ForeColor=TextSecondary;preview.Tag="SecondaryText";preview.AutoSize=false;preview.AutoEllipsis=true;preview.Size=new Size(364,104);preview.Location=new Point(18,92);preview.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;card.Controls.Add(preview);Button button=insane?insaneProgressApplyButton:progressApplyButton;ConfigureButton(button,insane?"Stage Insane":"Stage Normal",18,204,142,34);StyleButton(button,Good);button.Enabled=false;if(insane)button.Click+=delegate{TryUiAction(ApplySafeInsaneProgress);};else button.Click+=delegate{TryUiAction(ApplySafeNormalProgress);};card.Controls.Add(button);return card;}
    void BuildUnlockTab(){TabPage page=CreateTab("Profile");TableLayoutPanel layout=CreatePageLayout(page);Panel warning=NewCallout(0,0,820,76,"PROFILE UNLOCKS","These unlocks affect only your own local save/profile. They do not unlock items for other players.",Accent,Color.FromArgb(240,246,252));AddFullRow(layout,warning,76);Panel pets=BuildDualGlobalActionCard("Animal Orbs","Animal Orbs unlocked in your save profile.","Unlock All",delegate{TryUiAction(UnlockAllPets);},"Force Lock",delegate{TryUiAction(LockAllPets);});Panel weapons=BuildDualGlobalActionCard("Weapons","Weapons unlocked in your save profile.","Unlock All",delegate{TryUiAction(UnlockAllWeapons);},"Force Lock",delegate{TryUiAction(LockAllWeapons);});AddFullRow(layout,NewTwoColumnRow(pets,weapons),118);Panel items=BuildDualGlobalActionCard("Key Items","Bow • Boomerang • Shovel","Enable",delegate{TryUiAction(EnableKeyItems);},"Disable",delegate{TryUiAction(DisableKeyItems);});Panel everything=BuildDualGlobalActionCard("Everything","Every supported profile unlock in your save.","Unlock All",delegate{TryUiAction(UnlockEverything);},"Force Lock All",delegate{TryUiAction(ForceLockEverything);});AddFullRow(layout,NewTwoColumnRow(items,everything),118);Panel undo=NewCard(0,0,820,92);undo.Controls.Add(NewSectionTitle("Exact Undo",16,12));Label undoDesc=NewMutedLabel("Restore Latest returns the save to the most recent automatic backup.",16,42);undo.Controls.Add(undoDesc);Button latest=NewActionButton(undo,"Restore Latest",Good,delegate{TryUiAction(RestoreLatestBackup);});ConfigureButton(latest,"Restore Latest",650,28,152,40);latest.Anchor=AnchorStyles.Top|AnchorStyles.Right;AddFullRow(layout,undo,92);}
    Panel BuildDualGlobalActionCard(string title,string desc,string unlockText,EventHandler unlockHandler,string lockText,EventHandler lockHandler){Panel p=NewCard(0,0,400,118);p.Controls.Add(NewSectionTitle(title,16,12));Label d=NewMutedLabel(desc,16,42);d.AutoSize=false;d.AutoEllipsis=true;d.Size=new Size(188,56);p.Controls.Add(d);Button unlock=NewActionButton(p,unlockText,Warn,unlockHandler);ConfigureButton(unlock,unlockText,220,20,162,34);unlock.Anchor=AnchorStyles.Top|AnchorStyles.Right;Button lockButton=NewActionButton(p,lockText,Danger,lockHandler);ConfigureButton(lockButton,lockText,220,66,162,34);lockButton.Anchor=AnchorStyles.Top|AnchorStyles.Right;return p;}
    void BuildBackupsTab(){TabPage page=CreateTab("Backups");TableLayoutPanel layout=CreatePageLayout(page);Panel protectedBar=NewCallout(0,0,820,62,"BACKUPS","Backups are created automatically before writes. Restoring also creates a safety copy first.",Good,Color.FromArgb(239,249,241));AddFullRow(layout,protectedBar,62);Panel intro=NewCard(0,0,820,74);intro.Controls.Add(NewSectionTitle("Automatic Backups",16,10));backupInfo.Text="Load a save to view backups.";backupInfo.ForeColor=Muted;backupInfo.Tag="MutedText";backupInfo.AutoSize=false;backupInfo.AutoEllipsis=true;backupInfo.Size=new Size(786,26);backupInfo.Location=new Point(17,40);backupInfo.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;intro.Controls.Add(backupInfo);AddFullRow(layout,intro,74);backupList.View=View.Details;backupList.FullRowSelect=true;backupList.HideSelection=false;backupList.MultiSelect=false;backupList.SmallImageList=listRowSpacer;backupList.Font=new Font("Segoe UI",9.0f);backupList.Columns.Add("Backup",430);backupList.Columns.Add("Created",220);backupList.Columns.Add("Size",120);AddFullRow(layout,backupList,300);Panel actions=NewCard(0,0,820,112);Button latest=NewActionButton(actions,"Restore Latest",Good,delegate{TryUiAction(RestoreLatestBackup);});ConfigureButton(latest,"Restore Latest",16,18,128,38);Button restore=NewActionButton(actions,"Restore Selected",Warn,delegate{TryUiAction(RestoreSelectedBackup);});ConfigureButton(restore,"Restore Selected",154,18,140,38);Button refreshBackups=NewActionButton(actions,"Refresh",Accent,delegate{TryUiAction(RefreshBackups);});ConfigureButton(refreshBackups,"Refresh",304,18,92,38);Button open=NewActionButton(actions,"Open Folder",Accent,delegate{TryUiAction(OpenBackupFolder);});ConfigureButton(open,"Open Folder",406,18,112,38);Button del=NewActionButton(actions,"Delete Selected",Danger,delegate{TryUiAction(DeleteSelectedBackup);});ConfigureButton(del,"Delete Selected",528,18,146,38);Label legend=NewMutedLabel("Restore = return to backup  •  Delete = permanently remove selected backup",16,74);actions.Controls.Add(legend);AddFullRow(layout,actions,112);}
}
