
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using Microsoft.Win32;

public sealed partial class MainForm : Form
{
    void ApplyThemeToControl(Control control)
    {
        string role=control.Tag as string;
        if(control is Form){control.BackColor=Canvas;control.ForeColor=TextPrimary;}
        else if(control is TabPage){control.BackColor=Canvas;control.ForeColor=TextPrimary;}
        else if(control is TabControl){control.BackColor=Canvas;control.ForeColor=TextPrimary;}
        else if(control is TextBox){TextBox tb=(TextBox)control;tb.BackColor=InputSurface;tb.ForeColor=TextPrimary;tb.BorderStyle=BorderStyle.FixedSingle;}
        else if(control is ComboBox){ComboBox combo=(ComboBox)control;combo.BackColor=InputSurface;combo.ForeColor=TextPrimary;combo.FlatStyle=FlatStyle.Flat;if(combo.DrawMode!=DrawMode.OwnerDrawFixed){combo.DrawMode=DrawMode.OwnerDrawFixed;combo.DrawItem+=DrawComboItem;}}
        else if(control is ListView){ListView list=(ListView)control;list.BackColor=InputSurface;list.ForeColor=TextPrimary;list.BorderStyle=BorderStyle.FixedSingle;if(!list.OwnerDraw){list.OwnerDraw=true;list.DrawColumnHeader+=DrawListColumnHeader;list.DrawSubItem+=DrawListSubItem;list.DrawItem+=DrawListItem;}}
        else if(control is CheckBox){CheckBox cb=(CheckBox)control;cb.BackColor=control.Parent==null?Surface:control.Parent.BackColor;cb.ForeColor=TextPrimary;cb.FlatStyle=FlatStyle.Flat;cb.FlatAppearance.BorderColor=Border;}
        else if(control is Button){Button b=(Button)control;b.ForeColor=Color.White;b.UseVisualStyleBackColor=false;b.FlatStyle=FlatStyle.Flat;if(String.Equals(role,"HeaderButton",StringComparison.Ordinal)){b.BackColor=HeaderButton;b.ForeColor=HeaderText;b.FlatAppearance.BorderSize=1;b.FlatAppearance.BorderColor=HeaderBorder;}else if(!String.IsNullOrEmpty(role)&&role.StartsWith("Button:",StringComparison.Ordinal)){b.BackColor=SemanticColor(role.Substring("Button:".Length));b.FlatAppearance.BorderSize=0;}}
        else if(control is Label){if(String.Equals(role,"MutedText",StringComparison.Ordinal))control.ForeColor=Muted;else if(String.Equals(role,"SecondaryText",StringComparison.Ordinal))control.ForeColor=TextSecondary;else if(String.Equals(role,"HeaderPrimary",StringComparison.Ordinal))control.ForeColor=HeaderText;else if(String.Equals(role,"HeaderMuted",StringComparison.Ordinal))control.ForeColor=HeaderMuted;else if(!String.IsNullOrEmpty(role)&&role.StartsWith("AccentText:",StringComparison.Ordinal))control.ForeColor=SemanticTextColor(role.Substring("AccentText:".Length));else control.ForeColor=TextPrimary;if(control.Parent!=null)control.BackColor=control.Parent.BackColor;}
        else if(control is Panel||control is TableLayoutPanel||control is FlowLayoutPanel){if(String.Equals(role,"Header",StringComparison.Ordinal))control.BackColor=Header;else if(String.Equals(role,"Canvas",StringComparison.Ordinal))control.BackColor=Canvas;else if(String.Equals(role,"Card",StringComparison.Ordinal))control.BackColor=Surface;else if(String.Equals(role,"Callout",StringComparison.Ordinal))control.BackColor=SurfaceRaised;else if(!String.IsNullOrEmpty(role)&&role.StartsWith("AccentStripe:",StringComparison.Ordinal))control.BackColor=SemanticTextColor(role.Substring("AccentStripe:".Length));else if(control.Parent!=null)control.BackColor=control.Parent.BackColor;control.ForeColor=TextPrimary;}
        foreach(Control child in control.Controls)ApplyThemeToControl(child);
    }
    void ApplyNativeThemeRecursive(Control control){try{string subApp=darkMode?"DarkMode_Explorer":"Explorer";SetWindowTheme(control.Handle,subApp,null);}catch{}foreach(Control child in control.Controls)ApplyNativeThemeRecursive(child);}
    void ApplyImmersiveTitleBar(){try{int enabled=darkMode?1:0;int result=DwmSetWindowAttribute(Handle,20,ref enabled,sizeof(int));if(result!=0)DwmSetWindowAttribute(Handle,19,ref enabled,sizeof(int));}catch{}}
    void DrawTabItem(object sender,DrawItemEventArgs e){if(e.Index<0||e.Index>=tabs.TabPages.Count)return;bool selected=e.Index==tabs.SelectedIndex;Rectangle r=e.Bounds;Color background=selected?Surface:TabInactive;using(SolidBrush brush=new SolidBrush(background))e.Graphics.FillRectangle(brush,r);using(Pen pen=new Pen(Border))e.Graphics.DrawRectangle(pen,r.X,r.Y,Math.Max(0,r.Width-1),Math.Max(0,r.Height-1));Rectangle textRect=new Rectangle(r.X+8,r.Y+1,Math.Max(1,r.Width-16),Math.Max(1,r.Height-2));TextRenderer.DrawText(e.Graphics,tabs.TabPages[e.Index].Text.Replace("&&","&"),tabs.Font,textRect,selected?TextPrimary:Muted,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix);}
    void DrawComboItem(object sender,DrawItemEventArgs e){ComboBox combo=sender as ComboBox;if(combo==null)return;bool selected=(e.State&DrawItemState.Selected)==DrawItemState.Selected;Color background=selected?Accent:InputSurface;Color foreground=selected?Color.White:TextPrimary;using(SolidBrush brush=new SolidBrush(background))e.Graphics.FillRectangle(brush,e.Bounds);string text=e.Index>=0&&e.Index<combo.Items.Count?Convert.ToString(combo.Items[e.Index],CultureInfo.InvariantCulture):combo.Text;Rectangle textRect=new Rectangle(e.Bounds.X+5,e.Bounds.Y,Math.Max(1,e.Bounds.Width-8),e.Bounds.Height);TextRenderer.DrawText(e.Graphics,text??String.Empty,combo.Font,textRect,foreground,TextFormatFlags.Left|TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix);}
    void DrawListColumnHeader(object sender,DrawListViewColumnHeaderEventArgs e){using(SolidBrush brush=new SolidBrush(SurfaceRaised))e.Graphics.FillRectangle(brush,e.Bounds);using(Pen pen=new Pen(Border))e.Graphics.DrawRectangle(pen,e.Bounds.X,e.Bounds.Y,Math.Max(0,e.Bounds.Width-1),Math.Max(0,e.Bounds.Height-1));TextFormatFlags flags=TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix;if(e.Header.TextAlign==HorizontalAlignment.Center)flags|=TextFormatFlags.HorizontalCenter;else if(e.Header.TextAlign==HorizontalAlignment.Right)flags|=TextFormatFlags.Right;else flags|=TextFormatFlags.Left;Rectangle textRect=new Rectangle(e.Bounds.X+8,e.Bounds.Y,Math.Max(1,e.Bounds.Width-16),e.Bounds.Height);TextRenderer.DrawText(e.Graphics,e.Header.Text,((ListView)sender).Font,textRect,TextPrimary,flags);}
    void DrawListSubItem(object sender,DrawListViewSubItemEventArgs e){ListView list=sender as ListView;if(list==null)return;bool selected=e.Item.Selected;bool zebra=(e.ItemIndex%2)!=0;Color background=selected?Accent:(zebra?SurfaceRaised:InputSurface);Color foreground=selected?Color.White:e.Item.ForeColor;if(foreground.IsEmpty||foreground.ToArgb()==SystemColors.WindowText.ToArgb())foreground=TextPrimary;if(!selected&&list==characterList&&e.ColumnIndex==2){string state=e.SubItem.Text;if(String.Equals(state,"Locked",StringComparison.OrdinalIgnoreCase))foreground=DisabledText;else if(String.Equals(state,"Unlocked",StringComparison.OrdinalIgnoreCase))foreground=GoodTextColor;else if(String.Equals(state,"Starter",StringComparison.OrdinalIgnoreCase)||String.Equals(state,"DLC",StringComparison.OrdinalIgnoreCase))foreground=AccentTextColor;}using(SolidBrush brush=new SolidBrush(background))e.Graphics.FillRectangle(brush,e.Bounds);TextFormatFlags flags=TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix;HorizontalAlignment align=list.Columns[e.ColumnIndex].TextAlign;if(align==HorizontalAlignment.Center)flags|=TextFormatFlags.HorizontalCenter;else if(align==HorizontalAlignment.Right)flags|=TextFormatFlags.Right;else flags|=TextFormatFlags.Left;Rectangle textRect=new Rectangle(e.Bounds.X+8,e.Bounds.Y,Math.Max(1,e.Bounds.Width-16),e.Bounds.Height);TextRenderer.DrawText(e.Graphics,e.SubItem.Text,list.Font,textRect,foreground,flags);}
}
