
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using Microsoft.Win32;

public sealed partial class MainForm : Form
{
    void ApplyPendingChanges(){EnsureLoaded();if(HasInvalidVisibleInputs())throw new InvalidOperationException("Fix the highlighted invalid input before applying changes.");if(!HasPendingChanges()){SetStatus("No unsaved changes to apply.");UpdatePendingUi();return;}EnsureGameClosed();if(pendingDangerous&&!Confirm("Apply the pending staged changes now?\n\nOne backup will be created before the save is written."))return;string backup=SaveEncrypted();committedPlain=(byte[])session.Plain.Clone();pendingDangerous=false;ClearMaxAllCharacterSnapshot();ClearDraftInputsSilent();RefreshUiAfterWrite(SelectedIndex);UpdatePendingUi();SetStatus("Changes applied. Backup created: "+Path.GetFileName(backup));}
    void DiscardPendingChanges(){EnsureLoaded();if(!HasPendingChanges()){SetStatus("No unsaved changes to discard.");return;}if(!Confirm("Discard all unsaved changes and return to the last saved state?"))return;session.Plain=(byte[])committedPlain.Clone();pendingDangerous=false;ClearMaxAllCharacterSnapshot();ClearDraftInputsSilent();PopulateList();SelectCharacter(SelectedIndex);UpdateDetails();UpdatePendingUi();SetStatus("Unsaved changes discarded.");}
    bool ResolvePendingBeforeReload(string actionName){if(!HasPendingChanges())return true;DialogResult r=MessageBox.Show(this,"You have unsaved changes.\n\nYes = Apply them first\nNo = Discard them\nCancel = Stay here","Unsaved changes before "+actionName,MessageBoxButtons.YesNoCancel,MessageBoxIcon.Warning);if(r==DialogResult.Cancel)return false;if(r==DialogResult.Yes){ApplyPendingChanges();return!HasPendingChanges();}session.Plain=(byte[])committedPlain.Clone();pendingDangerous=false;ClearMaxAllCharacterSnapshot();ClearDraftInputsSilent();UpdatePendingUi();return true;}
    void MainForm_FormClosing(object sender,FormClosingEventArgs e){if(!HasPendingChanges())return;DialogResult r=MessageBox.Show(this,"You have unsaved changes.\n\nYes = Apply and exit\nNo = Discard and exit\nCancel = Keep Crasher Unlocker open","Unsaved changes",MessageBoxButtons.YesNoCancel,MessageBoxIcon.Warning);if(r==DialogResult.Cancel){e.Cancel=true;return;}if(r==DialogResult.Yes){try{ApplyPendingChanges();if(HasPendingChanges())e.Cancel=true;}catch(Exception ex){Log(ex.ToString());MessageBox.Show(this,ex.Message,"Crasher Unlocker V1.2",MessageBoxButtons.OK,MessageBoxIcon.Warning);e.Cancel=true;}}}
    void ClearInputs(){if(session!=null&&committedPlain!=null){int idx=SelectedIndex;foreach(string key in edits.Keys)RestoreTextFieldFromCommitted(key,idx);}ClearDraftInputsSilent();UpdatePendingUi();SetStatus("Current text-field edits cleared.");}
    void StageMaxStats(){string max=CurrentStatInputMax().ToString(CultureInfo.InvariantCulture);edits["Strength"].Text=max;edits["Magic"].Text=max;edits["Defense"].Text=max;edits["Agility"].Text=max;SetStatus("Max Stats staged at Castle Crashers' supported maximum (25) — not saved yet.");}
    void StageMaxItems(){edits["Potions"].Text="9";edits["Bombs"].Text="9";edits["Sandwiches"].Text="9";SetStatus("Max Items staged — not saved yet.");}
    void StageMaxCharacter(){StageMaxStats();StageMaxItems();SetStatus("Max combat values staged. Level, XP, and Gold were intentionally left unchanged.");}
    void LoadSave(){if(session!=null&&!ResolvePendingBeforeReload("loading a save"))return;session=FindAndOpenSave();committedPlain=(byte[])session.Plain.Clone();pendingDangerous=false;ClearMaxAllCharacterSnapshot();ClearDraftInputsSilent();savePathLabel.Text=session.Path;PopulateList();UpdateDetails();progressApplyButton.Enabled=true;insaneProgressApplyButton.Enabled=true;toggleButton.Enabled=IsToggleable(SelectedIndex);RefreshBackups();UpdatePendingUi();UpdateLoadAvailabilityUi();SetStatus("Save loaded. Make your edits, then press Apply Changes when you are ready.");}
    void RefreshSave(){if(session!=null&&!ResolvePendingBeforeReload("refreshing from disk"))return;int idx=SelectedIndex;session=FindAndOpenSave();committedPlain=(byte[])session.Plain.Clone();pendingDangerous=false;ClearMaxAllCharacterSnapshot();ClearDraftInputsSilent();savePathLabel.Text=session.Path;PopulateList();SelectCharacter(idx);UpdateDetails();RefreshBackups();UpdatePendingUi();UpdateLoadAvailabilityUi();SetStatus("Save refreshed from disk.");}
    void OpenSaveFolder(){string path=session!=null?session.Path:FindSaveCandidates().FirstOrDefault();if(String.IsNullOrEmpty(path))throw new InvalidOperationException("No Castle Crashers save location was found.");Process.Start("explorer.exe","/select,\""+path+"\"");}
    void ApplyChanges(){ApplyPendingChanges();} void ApplyEquipment(){StageEquipmentSelection();} void ApplyProgress(){throw new InvalidOperationException("Raw manual progress editing is disabled in Safe Progress mode.");}
    void ApplySafeNormalProgress(){EnsureLoaded();int idx=SelectedIndex,o=CharacterOffset(idx),current=CountProgressBits(session.Plain,o+0x0C),target=SelectedComboValue(normalProgressCombo);if(target<current)throw new InvalidOperationException("Safe Progress will not move story progress backward. Use Restore Latest or the Backups tab instead.");if(target==current){SetStatus("Normal Mode is already at that checkpoint.");return;}WriteProgressBits(session.Plain,o+0x0C,target);ApplyNormalPrerequisites(session.Plain,o,target);MarkPending("Normal Mode staged to "+ProgressDisplayName(target)+" for "+CharacterNames[idx],false);UpdateDetails();}
    void ApplySafeInsaneProgress(){EnsureLoaded();int idx=SelectedIndex,o=CharacterOffset(idx),current=CountProgressBits(session.Plain,o+0x18),target=SelectedComboValue(insaneProgressCombo);if(target<current)throw new InvalidOperationException("Safe Progress will not move Insane Mode backward. Use Restore Latest or the Backups tab instead.");if(target==current){SetStatus("Insane Mode is already at that checkpoint.");return;}if(target>0){WriteProgressBits(session.Plain,o+0x0C,17);ApplyNormalPrerequisites(session.Plain,o,17);session.Plain[o+0x17]=0x01;}WriteProgressBits(session.Plain,o+0x18,target);ApplyInsanePrerequisites(session.Plain,o,target);MarkPending("Insane Mode staged to "+ProgressDisplayName(target)+" for "+CharacterNames[idx],false);UpdateDetails();}
    void ToggleUnlock(){EnsureLoaded();int idx=SelectedIndex;if(!IsToggleable(idx))throw new InvalidOperationException("This slot is a starter/DLC slot and is not managed by the normal character unlock flag.");int o=CharacterOffset(idx);bool nowUnlocked=session.Plain[o]!=0x80;session.Plain[o]=nowUnlocked?(byte)0x80:(byte)0x00;MarkPending(CharacterNames[idx]+" staged as "+(nowUnlocked?"unlocked":"locked"),false);PopulateList();SelectCharacter(idx);UpdateDetails();}
    void CompleteNormal(){EnsureLoaded();int idx=SelectedIndex,o=CharacterOffset(idx);WriteProgressBits(session.Plain,o+0x0C,17);ApplyNormalPrerequisites(session.Plain,o,17);session.Plain[o+0x12]|=0x0F;session.Plain[o+0x17]=0x01;session.Plain[o+0x1B]=0x01;MarkPending("Complete Normal staged for "+CharacterNames[idx],false);UpdateDetails();}
    void CompleteInsane(){EnsureLoaded();int idx=SelectedIndex,o=CharacterOffset(idx);WriteProgressBits(session.Plain,o+0x0C,17);ApplyNormalPrerequisites(session.Plain,o,17);session.Plain[o+0x17]=0x01;WriteProgressBits(session.Plain,o+0x18,17);session.Plain[o+0x12]=0xFF;session.Plain[o+0x1B]=0xFF;MarkPending("Complete Insane staged for "+CharacterNames[idx],false);UpdateDetails();}
    void CompleteCharacter(){CompleteInsane();}
    int CountUnlockedNormalCharacters(){if(session==null)return 0;int count=0;for(int i=4;i<28;i++)if(session.Plain[CharacterOffset(i)]==0x80)count++;return count;}
}
