
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using Microsoft.Win32;

public sealed partial class MainForm : Form
{
    Control BuildStatusBar(){Panel host=new Panel();host.BackColor=Canvas;host.Tag="Canvas";host.Padding=new Padding(16,6,16,12);Panel bar=NewCard(0,0,100,46);bar.Dock=DockStyle.Fill;host.Controls.Add(bar);TableLayoutPanel layout=new TableLayoutPanel();layout.Dock=DockStyle.Fill;layout.Margin=Padding.Empty;layout.Padding=new Padding(10,5,10,5);layout.ColumnCount=5;layout.RowCount=1;layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,24f));layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100f));layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,180f));layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,158f));layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,122f));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100f));bar.Controls.Add(layout);Label dot=new Label();dot.Text="●";dot.ForeColor=AccentTextColor;dot.AutoSize=false;dot.Dock=DockStyle.Fill;dot.TextAlign=ContentAlignment.MiddleCenter;layout.Controls.Add(dot,0,0);statusText.Text="Ready.";statusText.ForeColor=TextSecondary;statusText.Tag="SecondaryText";statusText.AutoEllipsis=true;statusText.AutoSize=false;statusText.Dock=DockStyle.Fill;statusText.TextAlign=ContentAlignment.MiddleLeft;statusText.Margin=new Padding(2,0,10,0);layout.Controls.Add(statusText,1,0);pendingLabel.Text="No staged changes";pendingLabel.ForeColor=Muted;pendingLabel.Tag="MutedText";pendingLabel.Font=new Font("Segoe UI Semibold",9.0f);pendingLabel.AutoSize=false;pendingLabel.AutoEllipsis=true;pendingLabel.TextAlign=ContentAlignment.MiddleRight;pendingLabel.Dock=DockStyle.Fill;pendingLabel.Margin=new Padding(4,0,10,0);layout.Controls.Add(pendingLabel,2,0);ConfigureButton(applyPendingButton,"Apply Changes",0,0,100,32);StyleButton(applyPendingButton,Good);applyPendingButton.Dock=DockStyle.Fill;applyPendingButton.Margin=new Padding(0,0,8,0);applyPendingButton.Enabled=false;applyPendingButton.Click+=delegate{TryUiAction(ApplyPendingChanges);};layout.Controls.Add(applyPendingButton,3,0);ConfigureButton(discardPendingButton,"Discard",0,0,100,32);StyleButton(discardPendingButton,NeutralButton);discardPendingButton.Dock=DockStyle.Fill;discardPendingButton.Margin=Padding.Empty;discardPendingButton.Enabled=false;discardPendingButton.Click+=delegate{TryUiAction(DiscardPendingChanges);};layout.Controls.Add(discardPendingButton,4,0);return host;}
    Panel NewCard(int x,int y,int w,int h){Panel p=new Panel();p.Location=new Point(x,y);p.Size=new Size(w,h);p.BackColor=Surface;p.ForeColor=TextPrimary;p.BorderStyle=BorderStyle.FixedSingle;p.Tag="Card";return p;}
    Panel NewCallout(int x,int y,int w,int h,string title,string message,Color accent,Color background){Panel p=new Panel();p.Location=new Point(x,y);p.Size=new Size(w,h);p.BackColor=darkMode?SurfaceRaised:background;p.ForeColor=TextPrimary;p.BorderStyle=BorderStyle.FixedSingle;p.Tag="Callout";Panel stripe=new Panel();stripe.Location=new Point(0,0);stripe.Size=new Size(6,h);stripe.BackColor=accent;stripe.Tag="AccentStripe:"+SemanticRoleForColor(accent);stripe.Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left;p.Controls.Add(stripe);Label t=new Label();t.Text=title;t.Font=new Font("Segoe UI Semibold",10.0f);t.ForeColor=accent;t.Tag="AccentText:"+SemanticRoleForColor(accent);t.AutoSize=false;t.AutoEllipsis=true;t.Size=new Size(w-36,22);t.Location=new Point(16,8);t.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;p.Controls.Add(t);Label m=new Label();m.Text=message;m.ForeColor=TextSecondary;m.Tag="SecondaryText";m.AutoSize=false;m.AutoEllipsis=true;m.Size=new Size(w-36,Math.Max(22,h-35));m.Location=new Point(16,31);m.Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right;p.Controls.Add(m);return p;}
    Label NewSectionTitle(string text,int x,int y){Label l=new Label();l.Text=text;l.Font=new Font("Segoe UI Semibold",11.0f);l.ForeColor=TextPrimary;l.Tag="PrimaryText";l.AutoSize=true;l.Location=new Point(x,y);return l;}
    Label NewMutedLabel(string text,int x,int y){Label l=new Label();l.Text=text;l.ForeColor=Muted;l.Tag="MutedText";l.AutoSize=true;l.Location=new Point(x,y);return l;}
    void AddSummaryValue(Control parent,string key,string caption,int x,int y){Label cap=NewMutedLabel(caption,x,y);parent.Controls.Add(cap);Label val=new Label();val.Text="—";val.Font=new Font("Segoe UI Semibold",10.5f);val.ForeColor=TextPrimary;val.Tag="PrimaryText";val.AutoSize=false;val.AutoEllipsis=true;val.Size=new Size(150,25);val.Location=new Point(x,y+19);parent.Controls.Add(val);summary[key]=val;}
    void AddCompactSummaryValue(Control parent,string key,string caption,int x,int y,int width){Label cap=NewMutedLabel(caption,x,y);cap.AutoSize=false;cap.Size=new Size(width,20);parent.Controls.Add(cap);Label val=new Label();val.Text="—";val.Font=new Font("Segoe UI Semibold",10.5f);val.ForeColor=TextPrimary;val.Tag="PrimaryText";val.AutoSize=false;val.AutoEllipsis=true;val.Size=new Size(width,25);val.Location=new Point(x,y+22);parent.Controls.Add(val);summary[key]=val;}
    void AddEditField(Control parent,string key,string caption,int x,int y){Label l=new Label();l.Text=caption;l.AutoSize=false;l.Size=new Size(84,24);l.TextAlign=ContentAlignment.MiddleLeft;l.ForeColor=TextPrimary;l.Tag="PrimaryText";l.Location=new Point(x,y-2);parent.Controls.Add(l);TextBox tb=new TextBox();tb.Location=new Point(x+88,y-3);tb.Size=new Size(82,25);tb.BackColor=InputSurface;tb.ForeColor=TextPrimary;tb.BorderStyle=BorderStyle.FixedSingle;tb.Tag="Input";tb.TextChanged+=delegate{StageTextField(key,tb);};parent.Controls.Add(tb);edits[key]=tb;}
    static void ConfigureButton(Button b,string text,int x,int y,int w,int h){b.Text=text;b.Location=new Point(x,y);b.Size=new Size(w,h);}
    void StyleButton(Button b,Color color){b.UseVisualStyleBackColor=false;b.BackColor=color;b.ForeColor=Color.White;b.FlatStyle=FlatStyle.Flat;b.FlatAppearance.BorderSize=0;b.Tag="Button:"+SemanticRoleForColor(color);}
    string ThemePreferencePath(){string root=Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);return Path.Combine(root,"CrasherUnlocker","theme.txt");}
    void LoadThemePreference(){darkMode=true;try{string path=ThemePreferencePath();if(!File.Exists(path))return;string value=File.ReadAllText(path).Trim();if(String.Equals(value,"light",StringComparison.OrdinalIgnoreCase))darkMode=false;else if(String.Equals(value,"dark",StringComparison.OrdinalIgnoreCase))darkMode=true;}catch{}}
    void SaveThemePreference(){try{string path=ThemePreferencePath();string dir=Path.GetDirectoryName(path);if(!String.IsNullOrEmpty(dir))Directory.CreateDirectory(dir);File.WriteAllText(path,darkMode?"dark":"light");}catch{}}
}
