
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using Microsoft.Win32;

public sealed partial class MainForm : Form
{
    void BuildStatsTab()
    {
        TabPage page = CreateTab("Stats && Items");
        TableLayoutPanel layout = CreatePageLayout(page);
        Panel helper = NewCallout(0,0,820,62,"COMMON EDITS","Type only the values you want to change. Blank fields remain untouched.",Accent,Color.FromArgb(240,246,252));
        AddFullRow(layout,helper,62);
        Panel statsCard=NewCard(0,0,400,392); statsCard.Controls.Add(NewSectionTitle("Character Values",16,14));
        valueModeStateLabel.AutoSize=false; valueModeStateLabel.AutoEllipsis=true; valueModeStateLabel.Size=new Size(364,24); valueModeStateLabel.Location=new Point(18,48); valueModeStateLabel.TextAlign=ContentAlignment.MiddleLeft; valueModeStateLabel.Tag="PrimaryText"; statsCard.Controls.Add(valueModeStateLabel);
        valueModeRangeLabel.AutoSize=false; valueModeRangeLabel.AutoEllipsis=true; valueModeRangeLabel.Size=new Size(364,24); valueModeRangeLabel.Location=new Point(18,72); valueModeRangeLabel.TextAlign=ContentAlignment.MiddleLeft; valueModeRangeLabel.Tag="MutedText"; statsCard.Controls.Add(valueModeRangeLabel);
        currentLevelOverrideLabel.Text="Current: —"; currentLevelOverrideLabel.ForeColor=Muted; currentLevelOverrideLabel.Tag="MutedText"; currentLevelOverrideLabel.AutoSize=false; currentLevelOverrideLabel.AutoEllipsis=true; currentLevelOverrideLabel.Location=new Point(18,98); currentLevelOverrideLabel.Size=new Size(364,24); currentLevelOverrideLabel.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right; currentLevelOverrideLabel.TextAlign=ContentAlignment.MiddleLeft; statsCard.Controls.Add(currentLevelOverrideLabel);
        AddEditField(statsCard,"Level","Level",18,136); AddEditField(statsCard,"XP","XP",205,136); AddEditField(statsCard,"Gold","Gold",18,178); statsCard.Controls.Add(NewMutedLabel("Combat Stats",18,226)); AddEditField(statsCard,"Strength","Strength",18,260); AddEditField(statsCard,"Magic","Magic",205,260); AddEditField(statsCard,"Defense","Defense",18,302); AddEditField(statsCard,"Agility","Agility",205,302);
        Button maxStats=NewActionButton(statsCard,"Max Stats",Accent,delegate{StageMaxStats();}); ConfigureButton(maxStats,"Max Stats",18,340,118,34); Label statRange=NewMutedLabel("Only real game-supported values are available.",154,348); statRange.AutoSize=false; statRange.AutoEllipsis=true; statRange.Size=new Size(210,24); statsCard.Controls.Add(statRange);
        Panel itemsCard=NewCard(0,0,400,392); itemsCard.Controls.Add(NewSectionTitle("Consumables",16,14)); AddEditField(itemsCard,"Potions","Potions",18,58); AddEditField(itemsCard,"Bombs","Bombs",18,104); AddEditField(itemsCard,"Sandwiches","Sandwiches",18,150); Label itemRange=NewMutedLabel("Consumable range: 0–9",18,202); itemsCard.Controls.Add(itemRange); Button maxItems=NewActionButton(itemsCard,"Max Items",Accent,delegate{StageMaxItems();}); ConfigureButton(maxItems,"Max Items",18,270,118,34); Label safeNote=NewMutedLabel("All fields in this page follow real in-game limits.",154,272); safeNote.AutoSize=false; safeNote.AutoEllipsis=true; safeNote.Size=new Size(208,36); itemsCard.Controls.Add(safeNote); AddFullRow(layout,NewTwoColumnRow(statsCard,itemsCard),392);
        Panel balanceCard=NewCard(0,0,820,124); balanceCard.Controls.Add(NewSectionTitle("Character Balance",16,12)); balanceStateLabel.Text="Current: —"; balanceStateLabel.Font=new Font("Segoe UI Semibold",9.5f); balanceStateLabel.AutoSize=false; balanceStateLabel.AutoEllipsis=true; balanceStateLabel.Size=new Size(590,22); balanceStateLabel.Location=new Point(16,42); balanceStateLabel.TextAlign=ContentAlignment.MiddleLeft; balanceStateLabel.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right; balanceCard.Controls.Add(balanceStateLabel); balancePointsLabel.Text="Load a save first"; balancePointsLabel.ForeColor=Muted; balancePointsLabel.Tag="MutedText"; balancePointsLabel.AutoSize=false; balancePointsLabel.AutoEllipsis=true; balancePointsLabel.Size=new Size(590,22); balancePointsLabel.Location=new Point(16,70); balancePointsLabel.TextAlign=ContentAlignment.MiddleLeft; balancePointsLabel.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right; balanceCard.Controls.Add(balancePointsLabel); ConfigureButton(balanceCharacterButton,"Balance Character",630,48,172,40); balanceCharacterButton.Anchor=AnchorStyles.Top|AnchorStyles.Right; StyleButton(balanceCharacterButton,Accent); balanceCharacterButton.Enabled=false; balanceCharacterButton.Click+=delegate{TryUiAction(BalanceCharacter);}; balanceCard.Controls.Add(balanceCharacterButton); Label balanceNote=NewMutedLabel("Optional: normal manual edits are never auto-balanced.",16,98); balanceCard.Controls.Add(balanceNote); AddFullRow(layout,balanceCard,124);
        Panel actions=NewCard(0,0,820,68); ConfigureButton(statsApplyButton,"Apply All Changes",18,15,154,38); StyleButton(statsApplyButton,Good); statsApplyButton.Enabled=false; statsApplyButton.Click+=delegate{TryUiAction(ApplyPendingChanges);}; actions.Controls.Add(statsApplyButton); ConfigureButton(clearButton,"Clear Inputs",186,15,126,38); StyleButton(clearButton,NeutralButton); clearButton.Click+=delegate{ClearInputs();}; actions.Controls.Add(clearButton); Label note=NewMutedLabel("Apply writes all staged changes once.",338,25); actions.Controls.Add(note); AddFullRow(layout,actions,68);
    }

    Button NewActionButton(Control parent,string text,Color color,EventHandler handler){Button b=new Button();b.Text=text;StyleButton(b,color);b.Click+=handler;parent.Controls.Add(b);return b;}

    void BuildEquipmentTab()
    {
        TabPage page=CreateTab("Equipment"); TableLayoutPanel layout=CreatePageLayout(page); Panel safe=NewCallout(0,0,820,62,"EQUIPMENT","Only normal selectable equipment is shown. Special/internal weapon IDs remain hidden.",Good,Color.FromArgb(239,249,241)); AddFullRow(layout,safe,62);
        Panel card=NewCard(0,0,820,332); card.Controls.Add(NewSectionTitle("Selected Character Equipment",18,16)); Label weaponLabel=NewMutedLabel("Weapon",20,58); card.Controls.Add(weaponLabel); weaponCurrentLabel.ForeColor=Muted; weaponCurrentLabel.Tag="MutedText"; weaponCurrentLabel.AutoSize=false; weaponCurrentLabel.AutoEllipsis=true; weaponCurrentLabel.TextAlign=ContentAlignment.MiddleRight; weaponCurrentLabel.Location=new Point(390,52); weaponCurrentLabel.Size=new Size(410,24); weaponCurrentLabel.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right; card.Controls.Add(weaponCurrentLabel); weaponCombo.DropDownStyle=ComboBoxStyle.DropDownList; weaponCombo.Location=new Point(20,80); weaponCombo.Size=new Size(780,28); weaponCombo.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right; weaponCombo.SelectedIndexChanged+=delegate{StageEquipmentSelection();}; card.Controls.Add(weaponCombo);
        Label petLabel=NewMutedLabel("Animal Orb",20,132); card.Controls.Add(petLabel); petCurrentLabel.ForeColor=Muted; petCurrentLabel.Tag="MutedText"; petCurrentLabel.AutoSize=false; petCurrentLabel.AutoEllipsis=true; petCurrentLabel.TextAlign=ContentAlignment.MiddleRight; petCurrentLabel.Location=new Point(390,126); petCurrentLabel.Size=new Size(410,24); petCurrentLabel.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right; card.Controls.Add(petCurrentLabel); petCombo.DropDownStyle=ComboBoxStyle.DropDownList; petCombo.Location=new Point(20,154); petCombo.Size=new Size(780,28); petCombo.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right; petCombo.SelectedIndexChanged+=delegate{StageEquipmentSelection();}; card.Controls.Add(petCombo);
        Panel note=NewCallout(20,206,780,58,"NOTE","This changes only the selected character's equipped gear; it does not unlock the global collection.",Accent,Color.FromArgb(246,249,252)); note.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right; card.Controls.Add(note); ConfigureButton(equipmentApplyButton,"Apply All Changes",20,280,164,36); StyleButton(equipmentApplyButton,Good); equipmentApplyButton.Enabled=false; equipmentApplyButton.Click+=delegate{TryUiAction(ApplyPendingChanges);}; card.Controls.Add(equipmentApplyButton); AddFullRow(layout,card,332);
        Panel advancedHint=NewCard(0,0,820,96); advancedHint.Controls.Add(NewSectionTitle("Profile Unlocks",16,12)); Label advancedDesc=NewMutedLabel("Unlock or lock the weapon and Animal Orb collections stored in your own save profile.",16,42); advancedHint.Controls.Add(advancedDesc); Button go=NewActionButton(advancedHint,"Open Profile Unlocks",Accent,delegate{tabs.SelectedIndex=4;}); ConfigureButton(go,"Open Profile Unlocks",650,28,152,40); go.Anchor=AnchorStyles.Top|AnchorStyles.Right; AddFullRow(layout,advancedHint,96);
    }
}
